name: Build Android

on:
  push:
    branches:
      - master-prod-supabase

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: "21"

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 24.x

      - name: Install app dependencies
        run: npm install

      - name: Create Google Services JSON File and key.jks
        working-directory: ./android/app/
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON_PROD }}
          SHA_KEY: ${{ secrets.SHA_KEY_PROD }}
        run: |
          echo $GOOGLE_SERVICES_JSON | base64 -di > google-services.json
          echo $SHA_KEY | base64 -di > key.jks

      - name: Build
        env:
          CI: false
          REACT_APP_API_KEY: ${{ secrets.REACT_APP_API_KEY_PROD }}
          REACT_APP_AUTH_DOMAIN: ${{ secrets.REACT_APP_AUTH_DOMAIN_PROD }}
          REACT_APP_PROJECT_ID: ${{ secrets.REACT_APP_PROJECT_ID_PROD }}
          REACT_APP_STORAGE_BUCKET: ${{ secrets.REACT_APP_STORAGE_BUCKET_PROD }}
          REACT_APP_MESSAGING_SENDER_ID: ${{ secrets.REACT_APP_MESSAGING_SENDER_ID_PROD }}
          REACT_APP_APP_ID: ${{ secrets.REACT_APP_APP_ID_PROD }}
          REACT_APP_MEASUREMENT_ID: ${{ secrets.REACT_APP_MEASUREMENT_ID_PROD}}
          REACT_APP_ALGOLIA_APP_ID: ${{ secrets.REACT_APP_ALGOLIA_APP_ID }}
          REACT_APP_ALGOLIA_API_KEY: ${{ secrets.REACT_APP_ALGOLIA_API_KEY }}
          REACT_APP_HOT_UPDATE_SERVER: ${{ secrets.HOT_UPDATE_SERVER }}
          REACT_APP_ALGOLIA_INDEX_NAME: ${{ secrets.REACT_APP_ALGOLIA_INDEX_NAME_PROD}}
          REACT_APP_SUPABASE_URL: ${{ secrets.REACT_APP_PROD_SUPABASE_URL}}
          REACT_APP_SUPABASE_KEY: ${{ secrets.REACT_APP_PROD_SUPABASE_KEY}}
          REACT_APP_CLIENT_ID: ${{ secrets.REACT_APP_PROD_CLIENT_ID}}
          REACT_APP_RAPIDAPI_KEY: ${{ secrets.REACT_APP_RAPIDAPI_KEY }}
          REACT_APP_ENCRYPTION_KEY: ${{ secrets.REACT_APP_ENCRYPTION_KEY }}
          REACT_APP_GROWTHBOOK_ID: ${{ secrets.REACT_APP_GROWTHBOOK_ID_PROD }}
          REACT_APP_SENTRY_DSN: ${{ secrets.REACT_APP_SENTRY_DSN }}

        run: npm run build

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v13.0.3
        with:
          args: deploy --only hosting:cuba-stage-supabase-prod
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Make gradlew executable
        working-directory: ./android/
        run: chmod +x ./gradlew

      - name: Generate the Android App aab bundleRelease
        working-directory: ./android/
        run: ./gradlew bundleRelease

      - name: Generate the Android App apk (Release)
        working-directory: ./android/
        run: ./gradlew assembleRelease

      - name: Generate the Android App apk (Debug)
        working-directory: ./android/
        run: ./gradlew assembleDebug

      - name: Upload APKs and AAB to branch
        working-directory: .
        run: |
          git config --global user.email vinay@sutara.org
          git config --global user.name vinaypanduga

          TEMP_DIR=$(mktemp -d)
          cp android/app/build/outputs/bundle/release/app-release.aab $TEMP_DIR/
          cp android/app/build/outputs/apk/release/app-release.apk $TEMP_DIR/
          cp android/app/build/outputs/apk/debug/app-debug.apk $TEMP_DIR/

          cd $TEMP_DIR
          git init
          git remote add origin https://${{ secrets.ACCESS_TOKEN }}@github.com/chimple/cuba.git
          git checkout -b supabase-prod-apk
          git add .
          git commit -m "created apk and aab"
          git push origin supabase-prod-apk -f
